# Generated by Django 4.0.6 on 2022-07-12 06:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/images/default.png', max_length=255, verbose_name='image'),
        ),
    ]
