# Generated by Django 4.0.5 on 2022-07-06 11:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photos'),
        ),
    ]
