# Generated by Django 4.0.6 on 2022-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(null=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
