# Generated by Django 4.0.6 on 2022-07-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Singer_name',
            new_name='singer',
        ),
    ]
