# Generated by Django 4.0.6 on 2022-07-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
