# Generated by Django 4.0.6 on 2022-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0002_remove_song_song_song_audio_file_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.TextField(),
        ),
    ]
