# Generated by Django 4.0.6 on 2022-07-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0003_alter_song_artist_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iBeat.album'),
        ),
    ]
