# Generated by Django 4.0.6 on 2022-07-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0003_remove_post_post_post_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
