# Generated by Django 4.0.6 on 2022-07-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0004_delete_artist_remove_post_user_remove_song_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
