# Generated by Django 4.0.6 on 2022-07-11 18:03

from django.db import migrations, models
import iBeat.helper


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0004_delete_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='time_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='song/', validators=[iBeat.helper.validate_is_audio]),
        ),
    ]
