# Generated by Django 4.0.6 on 2022-07-11 18:56

from django.db import migrations, models
import django.db.models.deletion
import iBeat.helper


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0005_song_time_length_alter_song_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('artiste', models.CharField(max_length=500)),
                ('time_length', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('audio_file', models.FileField(upload_to='musics/', validators=[iBeat.helper.validate_is_audio])),
                ('cover_image', models.ImageField(upload_to='music_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_title',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iBeat.album'),
        ),
    ]
