# Generated by Django 4.0.6 on 2022-07-12 18:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0006_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
