# Generated by Django 4.0.6 on 2022-07-12 04:43

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import iBeat.helper


class Migration(migrations.Migration):

    dependencies = [
        ('iBeat', '0006_music_remove_song_album_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(upload_to='song/', validators=[iBeat.helper.validate_is_audio])),
                ('time_length', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('song_title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.FileField(null=True, upload_to='album_logo/'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iBeat.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iBeat.artist'),
        ),
    ]
